zuul:
  add-proxy-headers: true
  ignored-services: '*'
  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 20000
  routes:
    EurekaServer:
      service-id: EurekaServer
      path: /gateway/eureka/**
      url: http://localhost:8761
    ConfigServer:
      service-id: ConfigServer
      path: /gateway/config/**
      url: http://localhost:8888
    servicelogin:
      service-id: servicelogin
      path: /gateway/services/**
      url: http://localhost:8005

ribbon:
  eureka:
    enabled: false