eureka:
  client:
    preferSameZoneEureka: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    register-with-eureka: false
    fetch-registry: false
    healthcheck:
      enabled: true
  instance:
    hostname: localhost
    metadataMap:
      zone: zone1
    statusPageUrl: https://${eureka.hostname}/info
    healthCheckUrl: https://${eureka.hostname}/health
    homePageUrl: https://${eureka.hostname}/