#---
#
#spring:
#  profiles: local
#  cloud:
#    config:
#      server:
#        git:
#          uri: file:///X:/dev/GITHUB/LoginMeDummy/servicelogin.properties
#          default-label: main
#          timeout: 4
#
#---
#
#spring:
#  profiles: dev
#
#---
#
#spring:
#  profiles: pro
