server:
  port: 8888

spring:
  application:
    name: ConfigServer
  cloud:
    config:
      server:
        git:
          uri: file:///C:/Entorno/dev/GITHUB/LoginMeDummy/config
          # 
          # https://github.com/JavierLobo/loginmedummy/config
profiles:
  active: dev