info:
  component: Servicio de login

spring:
  application:
    name: servicelogin
  cloud:
    config:
      uri: http://localhost:8888
      fail-fast: true             #the service will not run if it can't reach the config-service
  
server:
  port: 0

eureka:
  instance:
    instance-id: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}

cloud:
  services:
    registrationMethod: route