spring:
  application:
    name: servicelogin
  cloud:
    config:
      uri:      - http://localhost:8888
  
info:
  component: Servicio de login
  
server:
  port: 0

eureka:
  instance:
    instance-id: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}

cloud:
  services:
    registrationMethod: route